name: Build client and deploy to azure blob
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: cd client
      - run: yarn
      - run: yarn build
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: 'build'
          container_name: '$web'
          connection_string: ${{ secrets.ConnectionString }}
          sync: 'true'
